feature: batsw self-contained wrapper to run Bats (Bash Automated Testing System) tests

diff --git a/batsw b/batsw
--- a/batsw
+++ b/batsw
@@ -1,1 +1,83 @@
-# TODO
+#!/usr/bin/env bash
+#
+# Bats Wrapper — self-contained wrapper to run Bats (Bash Automated Testing System) tests
+# https://github.com/bkahlert/bats-wrapper
+#
+# MIT License
+#
+# Copyright (c) 2021 Dr. Björn Kahlert
+#
+# Permission is hereby granted, free of charge, to any person obtaining a copy
+# of this software and associated documentation files (the "Software"), to deal
+# in the Software without restriction, including without limitation the rights
+# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
+# copies of the Software, and to permit persons to whom the Software is
+# furnished to do so, subject to the following conditions:
+#
+# The above copyright notice and this permission notice shall be included in all
+# copies or substantial portions of the Software.
+#
+# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
+# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
+# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
+# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
+# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
+# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
+# SOFTWARE.
+
+# Usage: curl -LfsS https://git.io/batsw | "$SHELL" -s -- [OPTIONS] [DIR[/ ]FILE [FILE...]]
+# Local: ./batsw --batsw:-v --batsw:"$PWD/bats":/usr/local/bin/bats --batsw:-v --batsw:"$PWD/logr.sh":/usr/local/bin/logr.sh [OPTIONS] [DIR[/ ]FILE [FILE...]]
+
+if [ "${DOCKER_BAKE-}" ]; then
+  bake() {
+    echo "🐳 building Docker image:" "$@" >&2
+    if ! docker buildx bake "$@" >&2; then
+      printf ' %s %s\n' "$(tput setaf 1)✘$(tput sgr0)" "failed to bake Docker image" >&2
+      exit 1
+    fi
+    docker images --format='{{.ID}}' | head -1
+  }
+  echo "🐳 built Docker image: $(eval bake "$DOCKER_BAKE")" >&2
+fi
+
+declare wrapper_name=${0##*/}
+declare -a args=() wrapper_args=()
+while (($#)); do
+  case $1 in
+    --${wrapper_name?}:*)
+      wrapper_args+=("${1#--${wrapper_name?}:}")
+      ;;
+    *)
+      args+=("$1")
+      ;;
+  esac
+  shift
+done
+set -- "${args[@]}"
+
+declare -a opts=()
+opts+=("-e" "TESTING=1")
+opts+=("-e" "RECORDING=${RECORDING-}")
+opts+=("-e" "TERM=${TERM-}")
+opts+=("-e" "TMPDIR=${BATS_TMPDIR:-$PWD/build/bats-tmp}")
+
+# Adds the given arguments to the opts array
+opts() { eval 'opts+=("$@")'; }
+[ ! -t 0 ] || opts+=("--interactive")
+[ ! -t 1 ] || [ ! -t 2 ] || [ "${TERM-}" = dumb ] || opts+=("--tty")
+[ ! -v BATSW_ARGS ] || eval opts "$BATSW_ARGS"
+opts+=("${wrapper_args[@]}")
+opts+=("--rm")
+opts+=("--name" "$wrapper_name--$(head /dev/urandom | LC_ALL=C.UTF-8 tr -dc A-Za-z0-9 2>/dev/null | head -c 3)")
+opts+=("${BATSW_IMAGE:-bkahlert/bats-wrapper:${BATSW_IMAGE_TAG:-latest}}")
+
+docker run \
+  -e DEBUG="${DEBUG-}" \
+  -e TZ="$(date +"%Z")" \
+  -e PUID="$(id -u)" \
+  -e PGID="$(id -g)" \
+  -v /var/run/docker.sock:/var/run/docker.sock \
+  -v "$PWD":"$PWD" \
+  -w "$PWD" \
+  "${opts[@]+"${opts[@]}"}" \
+  "$@"
